---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name:
    apt:
       name: "{mywebpackonubuntu}"
       state: present
       update_cache: yes
    when: ansible_os_family == "Debian"
  - name:
    service:
       name: "{mywebpackonubuntu}"
       state: stopped
    when: ansible_os_family == "Debian"