---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: Install java on Ubuntu
    apt:
     name: "{{myjavapackonubuntu}}"
     state: present
    when: ansible_os_family == "Debian"
