---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to uninstall java on Ubuntu
    apt:
     name: "{{myjavapackonubuntu}}"
     state: absent
    loop:
      - openjdk-8-jdk
    when: ansible_os_family == "Debian"
