---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install apache2
    apt: 
     name: apache2
     state: present
  notify: stop apache2
  handlers:
    - name: stop apache2
      service:
        name: apache2
        state: stopped
