---
- hosts: all
  become: yes
  tasks:
  - name: Install apache2 webserver
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"   
  - name: start apache2 services
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian" 