---
- name: Install apache2 on ubuntu
  hosts: all
  become: yes
  tasks:
  - name: Update APT Package cache
    apt:
     update_cache: yes
  - name: Install apache httpd  (state=present is optional)
    ansible.builtin.apt:
     name: apache2
     state: present
  - name: start apache2
    service:
     name: apache2
     state: started 
     enabled: yes  

      