---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - name: install git
    apt: 
     name: git
     state: present
    notify: stop git
  handlers:
    - name: stop git
      service:
        name: git
        state: absent
