---
- hosts: all
  become: yes
  tasks:
  - name: Install apache2 webserver
    apt:
     name: apache2
     state: present
  - name: start apache2 services
    service:
      name: apache2
      state: started
      