---
- hosts: all
  become: yes
  tasks:
  - name: this task,i want to install apache2
    apt:
     name: apache2
     state: present
  - name: this task,i want to start apache2 services
    service:
      name: apache2
      state: started
      enabled: yes