---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: in this task,install apache2 
    apt:
     name: apache2
     state: present
    when: ansible_os_family=='Debian'
  - name: in tis task,start apache2 service
    service:
       name: apache2
       state: started
    when: ansible_os_family=='Debian'
