---
- hosts: all
  become: yes
  tasks:
  - name: Install apache2 webserver
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"   
  - name: start apache2 services
    service:
      name: apache2
      state: started
    notify: restart webservers  
    when: ansible_os_family == "Debian" 
  handlers:
    - name: restart webservers
      service:
         name: apache2
         state: restarted