---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - name: install apache2
    apt: 
     name: apache2
     state: present
    notify: start apache2
  handlers:
    - name: start apache2
      service:
        name: apache2
        state: started
