---
- hosts: mywebservers
  become: yes
  tasks:
  - name: i want to install webserver
    apt: 
     name: apache2
     state: present
    notify: restartwebserver
  - name: copy index file into node site 
    template:
      src: myindexfile.j2
      dest: /var/www/html/index.html
  handlers:
  - name: restartwebserver
    service:
       name: apache2
       state: restarted  
