---
- hosts: 10.0.0.5,10.0.0.6
  become: yes
  tasks:
  - include_tasks: myfile.yml
  handlers:
    - name: restart webservers
      service:
         name: apache2
         state: restarted
         