---
- hosts: mywebservers
  become: yes
  tasks:
  - name: download internet files
    get_url: 
       url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
       dest: /home/maha/apache-tomcat-10.0.20.tar.gz
       force_basic_auth: yes
  
  
