---
- hosts: mywebservers
  become: yes
  tasks:
  - name: remove java
    apt:
     name: "{{myjavapackonubuntu}}"
     state: absent
  - name: remove java path
    shell: rm-rf  /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java