---
- hosts: mywebservers
  become: yes
  tasks:
  - name: uninstall JDK on ubuntu
    apt:
     name: "{{myjavapackonubuntu}}"
     state: absent
  - name: remove java path
    shell: rm -rf  /usr/lib/jvm/java-8-openjdk-amd64