---
- hosts: all
  become: yes
  tasks:
  - name: Install vsftpd
    apt:
     name: vsftpd
     state: present
     update_cache: yes
    when: ansible_os_family == 'Debian'
  
  - name: start vsftpd services
    service:
       name: vsftpd
       state: started